### ISSUE TITLE
Does not install with pip for Python 3.11

### ISSUE THREAD

**Issue by jmcarter17** [dstein64/kmeans1d#6]
Currently, kmeans1d does not install for python 3.11 using pip.

It fails to build the c++ library with clang. It could simply be a setup in my clang compiler,
But I think for python 3.10, it didn't need to compile it at all.

**Comment by dstein64** [comment]
Thanks for letting me know!

I just uploaded wheels for Python 3.11 to PyPI.

Installing again should resolve the issue. In case there is still a problem, try `pip install --no-cache-dir kmeans1d` in case `pip` tries to use cached source code instead of retrying to get the wheels.

**Comment by jmcarter17** [comment]
Wow, that was quick.

It works, thanks.
